/* eslint-disable import/prefer-default-export */
export const ROUTES = {
  Home: '/',
  Opleiding: '/opleiding',
  Programma: '/programma',
  ProgrammaDetail: '/programma/:programmeId',
  Werkstukken: '/werkstukken',
  WerkstukkenDetail: '/werkstukken/:werkstukkenId',
  Blog: '/blog',
  BlogDetail: '/blog/:postId',
  Services: '/services',
  SerciceDetail: '/services/:serviceId',
  Team: '/team',
  TeamDetail: '/team/:teamId',
  AUTH_SIGN_UP: '/auth/signup',
  AUTH_SIGN_IN: '/auth/signin',
  USER: '/user',
  USER_PROFILE: '/user/profile',
  FOUROFOUR: '/404',
};
