import {GET_AUTHUSER, GET_ALLAUTHUSER, GET_ALLBLOGS, GET_BLOG, GET_EDUCATION_PROGRAM, GETALLEDUCATIONPROGRAMME} from './queries'


export {
    GET_AUTHUSER, 
    GET_ALLAUTHUSER, 
    GET_ALLBLOGS,
    GET_BLOG,
    GET_EDUCATION_PROGRAM,
    GETALLEDUCATIONPROGRAMME
}
