import {GET_AUTHUSER, GET_ALLAUTHUSER, GET_ALLBLOGS, GET_BLOG, FIRST_BLOGS, GET_EDUCATION_PROGRAM, GETALLEDUCATIONPROGRAMME, GET_ALL_AUTHUSERS, GET_TRAININGS, FIRST_TRAINING, GET_ALL_WORKPIECES, GET_ID_WORKPIECE, FIRST_WORKPIECE, GET_ALL_SERVICES, FIRST_SERVICES} from './queries'


export {
    GET_AUTHUSER, 
    GET_ALLAUTHUSER, 
    GET_ALLBLOGS,
    GET_BLOG,
    FIRST_BLOGS,
    GET_EDUCATION_PROGRAM,
    GETALLEDUCATIONPROGRAMME,
    GET_ALL_AUTHUSERS,
    GET_TRAININGS,
    FIRST_TRAINING,
    GET_ALL_WORKPIECES,
    GET_ID_WORKPIECE,
    FIRST_WORKPIECE,
    GET_ALL_SERVICES,
    FIRST_SERVICES
}
